logging:
    level:
        com.disaster.mapper: debug # print database's log

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/disastermanager?serverTimezone=UTC&rewriteBatchedStatements=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 0
    mvc:
        hiddenmethod.filter.enabled: true
# mybatis
mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
